import { currentUser } from "@/lib/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { audit } from "@/lib/audit";
import { validCsrf } from "@/lib/security";
const buckets={"website-media":{max:50*1024*1024,types:["image/jpeg","image/png","image/webp","image/gif","image/svg+xml","video/mp4","video/webm","video/ogg"]},"private-documents":{max:50*1024*1024,types:["application/pdf","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","text/csv"]}} as const;
type Bucket=keyof typeof buckets;
async function staff(){const user=await currentUser();return user&&user.status==="ACTIVE"&&["OWNER","ADMINISTRATOR","EDITOR"].includes(user.role)?user:null}
export async function GET(request:Request){const user=await staff();if(!user)return Response.json({error:"Staff access required"},{status:403});const bucket=new URL(request.url).searchParams.get("bucket") as Bucket;if(!(bucket in buckets))return Response.json({error:"Invalid bucket"},{status:400});const admin=createAdminClient();const{data,error}=await admin.storage.from(bucket).list("",{limit:100,sortBy:{column:"created_at",order:"desc"}});if(error)return Response.json({error:error.message},{status:400});const files=await Promise.all((data||[]).filter(f=>f.id).map(async f=>{if(bucket==="website-media")return{...f,url:admin.storage.from(bucket).getPublicUrl(f.name).data.publicUrl};const{data:signed}=await admin.storage.from(bucket).createSignedUrl(f.name,300);return{...f,url:signed?.signedUrl||null}}));return Response.json({files})}
export async function POST(request:Request){const user=await staff();if(!user)return Response.json({error:"Staff access required"},{status:403});if(!await validCsrf(request))return Response.json({error:"Invalid CSRF token"},{status:403});const form=await request.formData();const bucket=String(form.get("bucket")) as Bucket;const file=form.get("file");if(!(bucket in buckets)||!(file instanceof File))return Response.json({error:"Invalid upload"},{status:400});const rules=buckets[bucket];if(file.size>rules.max||!(rules.types as readonly string[]).includes(file.type))return Response.json({error:"File type or size is not allowed"},{status:400});const clean=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}-${clean}`;const{error}=await createAdminClient().storage.from(bucket).upload(path,file,{contentType:file.type,cacheControl:bucket==="website-media"?"31536000":"3600",upsert:false});if(error)return Response.json({error:error.message},{status:400});await audit("FILE_UPLOADED",user.id,undefined,{bucket,path});return Response.json({ok:true,path},{status:201})}
export async function DELETE(request:Request){const user=await staff();if(!user)return Response.json({error:"Staff access required"},{status:403});if(!await validCsrf(request))return Response.json({error:"Invalid CSRF token"},{status:403});const body=await request.json().catch(()=>null) as {bucket?:Bucket,path?:string}|null;if(!body?.bucket||!(body.bucket in buckets)||!body.path||body.path.includes(".."))return Response.json({error:"Invalid file"},{status:400});const{error}=await createAdminClient().storage.from(body.bucket).remove([body.path]);if(error)return Response.json({error:error.message},{status:400});await audit("FILE_DELETED",user.id,undefined,body);return Response.json({ok:true})}
