import { currentUser } from "@/lib/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { validCsrf } from "@/lib/security";
import { audit } from "@/lib/audit";
async function staff(){const u=await currentUser();return u&&u.status==="ACTIVE"&&["OWNER","ADMINISTRATOR","EDITOR"].includes(u.role)?u:null}
export async function GET(){const u=await staff();if(!u)return Response.json({error:"Staff access required"},{status:403});const db=createAdminClient();const[{data:pages},{data:settings},{data:videos}]=await Promise.all([db.from("cms_pages").select("*").order("path"),db.from("site_settings").select("*").eq("id","global").maybeSingle(),db.from("cms_videos").select("*").order("sort_order")]);return Response.json({pages:pages||[],settings,videos:videos||[]})}
export async function PUT(request:Request){const u=await staff();if(!u)return Response.json({error:"Staff access required"},{status:403});if(!await validCsrf(request))return Response.json({error:"Invalid CSRF token"},{status:403});const b=await request.json().catch(()=>null);if(!b?.kind)return Response.json({error:"Invalid content"},{status:400});const db=createAdminClient();let error;if(b.kind==="page"){if(typeof b.value?.path!=="string"||!b.value.path.startsWith("/")||!b.value.title)return Response.json({error:"Path and title are required"},{status:400});({error}=await db.from("cms_pages").upsert({...b.value,updated_by:u.id,updated_at:new Date().toISOString()}))}else if(b.kind==="settings"){({error}=await db.from("site_settings").upsert({id:"global",...b.value,updated_by:u.id,updated_at:new Date().toISOString()}))}else return Response.json({error:"Invalid content type"},{status:400});if(error)return Response.json({error:error.message},{status:400});await audit("CMS_CONTENT_UPDATED",u.id,undefined,{kind:b.kind,path:b.value?.path});return Response.json({ok:true})}
export async function POST(request:Request){const u=await staff();if(!u)return Response.json({error:"Staff access required"},{status:403});if(!await validCsrf(request))return Response.json({error:"Invalid CSRF token"},{status:403});const b=await request.json().catch(()=>null);if(!b?.title||!b?.video_url)return Response.json({error:"Title and video URL are required"},{status:400});const{data,error}=await createAdminClient().from("cms_videos").insert({...b,updated_by:u.id}).select().single();if(error)return Response.json({error:error.message},{status:400});await audit("CMS_VIDEO_CREATED",u.id,undefined,{id:data.id});return Response.json({video:data},{status:201})}
export async function DELETE(request:Request){const u=await staff();if(!u)return Response.json({error:"Staff access required"},{status:403});if(!await validCsrf(request))return Response.json({error:"Invalid CSRF token"},{status:403});const{id}=await request.json().catch(()=>({}));if(!id)return Response.json({error:"Video ID required"},{status:400});const{error}=await createAdminClient().from("cms_videos").delete().eq("id",id);if(error)return Response.json({error:error.message},{status:400});await audit("CMS_VIDEO_DELETED",u.id,undefined,{id});return Response.json({ok:true})}
