import "server-only";
import { createClient } from "@/lib/supabase/server";
import { pageMap, type SitePage } from "@/lib/site-content";

export type SiteSettings={organizationName:string;logoUrl:string;contactEmail:string;heroTitle:string;heroDescription:string;heroVideoUrl:string};
export const defaultSettings:SiteSettings={organizationName:"Francis Koroma Foundation",logoUrl:"/fkf-logo.png",contactEmail:"info@franciskoromafoundation.org",heroTitle:"Empowering the Next Generation of Global Leaders and Changemakers",heroDescription:"The Francis Koroma Foundation is a U.S.-based 501(c)(3) nonprofit organization committed to helping young people successfully navigate the transition into adulthood through academic support, mentorship opportunities, leadership training, and personal development initiatives.",heroVideoUrl:"https://www.youtube.com/embed/De-BByJLQxw?autoplay=1&mute=1&loop=1&playlist=De-BByJLQxw&controls=0&modestbranding=1"};
export async function getSiteSettings(){try{const{data}=await(await createClient()).from("site_settings").select("*").eq("id","global").maybeSingle();if(!data)return defaultSettings;return{organizationName:data.organization_name,logoUrl:data.logo_url,contactEmail:data.contact_email,heroTitle:data.hero_title,heroDescription:data.hero_description,heroVideoUrl:data.hero_video_url} as SiteSettings}catch{return defaultSettings}}
export async function getCmsPage(path:string){const fallback=pageMap.get(path);try{const{data}=await(await createClient()).from("cms_pages").select("*").eq("path",path).eq("published",true).maybeSingle();if(!data)return fallback;return{path:data.path,eyebrow:data.eyebrow,title:data.title,description:data.description,image:data.image||undefined,sections:Array.isArray(data.sections)?data.sections:[],cta:data.cta||undefined} as SitePage}catch{return fallback}}
export type CmsVideo={id:string;title:string;description:string;video_url:string;thumbnail_url:string|null};
export async function getCmsVideos(){try{const{data}=await(await createClient()).from("cms_videos").select("id,title,description,video_url,thumbnail_url").eq("published",true).order("sort_order");return(data||[]) as CmsVideo[]}catch{return[]}}
