export type SitePage = {
  path: string;
  eyebrow: string;
  title: string;
  description: string;
  sections: { title: string; body: string; items?: string[] }[];
  image?: string;
  cta?: { label: string; href: string };
};

export const siteUrl = "https://franciskoromafoundation.org";

export const pages: SitePage[] = [
  { path: "/about", eyebrow: "Who We Are", title: "About the Foundation", description: "A 501(c)(3) nonprofit empowering the next generation of global leaders and changemakers.", image: "/about/about-image.jpg", sections: [{ title: "Our Mission", body: "The Francis Koroma Foundation provides academic support, mentorship, leadership development, and community engagement that help young people become effective leaders for society." }, { title: "Our Vision", body: "We envision a just and equitable society where every young person can access the education, resources, and opportunities needed to reach their full potential." }, { title: "Our Values", body: "Our work is grounded in leadership, integrity, service, innovation, collaboration, and empowerment.", items: ["Education", "Mentorship", "Leadership", "Community service"] }], cta: { label: "Support our mission", href: "/support-us" } },
  { path: "/about/board-of-directors", eyebrow: "Leadership", title: "Board of Directors", description: "Experienced leaders guiding the Foundation’s mission and global impact.", image: "/leadership/hawa.jpg", sections: [{ title: "Purpose-led governance", body: "Our board provides strategic oversight and brings experience in international development, humanitarian service, climate action, education, and community leadership." }, { title: "Meet the board", body: "Learn more about the directors and their experience on our leadership page." }], cta: { label: "View leadership", href: "/about/leadership" } },
  { path: "/programs", eyebrow: "Foundation Programs", title: "Empowering Young Leaders", description: "Programs that expand opportunity through education, mentorship, service, and meaningful conversation.", image: "/focus/mentorship.jpg", sections: [{ title: "Our approach", body: "FKF programs connect young people with practical support, trusted mentors, leadership opportunities, and communities committed to their success." }, { title: "Program areas", body: "Explore the Foundation’s core public programs.", items: ["Mentorship Program", "Scholarship Program", "Community Service", "FKF Speaker Series"] }], cta: { label: "Explore mentorship", href: "/programs/mentorship" } },
  { path: "/programs/mentorship", eyebrow: "Foundation Programs", title: "Mentorship Program", description: "Connecting emerging leaders with guidance, encouragement, and a global community.", image: "/focus/mentorship.jpg", sections: [{ title: "Guidance that matters", body: "The mentorship program helps young people navigate education, professional growth, leadership, and service with support from experienced mentors." }, { title: "What participants gain", body: "Mentorship is centered on practical development and sustained encouragement.", items: ["Goal setting", "Leadership development", "Academic and career guidance", "Global connections"] }], cta: { label: "Volunteer as a mentor", href: "/volunteer" } },
  { path: "/programs/scholarship", eyebrow: "Foundation Programs", title: "Scholarship Program", description: "Helping students pursue education and build pathways to lasting impact.", image: "/focus/academic.jpg", sections: [{ title: "Opportunity through education", body: "The FKF Scholarship Program supports the Foundation’s commitment to reducing barriers and helping promising young people continue their education." }, { title: "Applications", body: "Scholarship application workflows will be introduced in Phase 2. Public announcements and eligibility details will be published here when a cycle opens." }], cta: { label: "View resources", href: "/resources" } },
  { path: "/programs/community-service", eyebrow: "Foundation Programs", title: "Community Service", description: "Mobilizing young leaders to create practical, positive change in their communities.", image: "/impact/impact-5.jpg", sections: [{ title: "Service in action", body: "Community service initiatives turn leadership into action by responding to local needs and strengthening a culture of civic responsibility." }, { title: "How we serve", body: "Projects are designed around collaboration and sustainable community benefit.", items: ["Youth-led service", "Community partnerships", "Local outreach", "Sustainable impact"] }], cta: { label: "Get involved", href: "/volunteer" } },
  { path: "/programs/speaker-series", eyebrow: "Foundation Programs", title: "FKF Speaker Series", description: "Conversations with leaders, advocates, and changemakers shaping a better future.", image: "/founder/message.jpg", sections: [{ title: "Ideas that inspire action", body: "The speaker series creates space for honest conversations about leadership, education, innovation, service, and global challenges." }, { title: "Who it serves", body: "Sessions connect young people and communities with ideas, lived experience, and practical encouragement." }], cta: { label: "Watch videos", href: "/videos" } },
  { path: "/impact-news", eyebrow: "News & Impact", title: "FKF Impact News", description: "Stories, announcements, and updates from across the Foundation’s work.", image: "/impact/impact-featured.jpg", sections: [{ title: "Foundation updates", body: "This page preserves a public home for FKF announcements and impact stories while a full content management workflow is planned for Phase 2." }, { title: "Stay connected", body: "Follow the Foundation’s official social channels and check back for program news, events, and community highlights." }], cta: { label: "See our gallery", href: "/gallery" } },
  { path: "/gallery", eyebrow: "Media", title: "Gallery", description: "Moments from FKF programs, partnerships, leadership, and community service.", image: "/founder/african.JPG", sections: [{ title: "Our work in pictures", body: "Authentic Foundation photography documents the people, places, and partnerships behind our mission." }, { title: "Featured moments", body: "Explore highlights from youth programs, speaking engagements, service projects, and international advocacy.", items: ["Programs", "Community", "Leadership", "Global engagement"] }], cta: { label: "Watch videos", href: "/videos" } },
  { path: "/videos", eyebrow: "Media", title: "Videos", description: "Watch conversations, program highlights, and stories from the Francis Koroma Foundation.", image: "/founder/hero.jpg", sections: [{ title: "FKF on video", body: "Video updates and public recordings are available through the Foundation’s official YouTube channel." }, { title: "Stories and conversations", body: "Discover leadership insights, community highlights, and messages that advance the Foundation’s mission." }], cta: { label: "Visit YouTube", href: "https://www.youtube.com/channel/UCKZT3HpsOhZ_r1TmU2sY7Og" } },
  { path: "/resources", eyebrow: "Resources", title: "Resources", description: "Learning and opportunity resources that support education, leadership, and sustainable development.", image: "/sdg/sdg-wheel.png", sections: [{ title: "Knowledge for action", body: "FKF shares trusted resources that help young people and partner organizations learn, grow, and contribute to sustainable development." }, { title: "Resource areas", body: "Explore materials aligned with our mission.", items: ["SDGs 2030 resources", "Educational materials", "Free university courses", "Partnership opportunities"] }], cta: { label: "Explore the SDGs", href: "https://globalgoals.org/goals/" } },
  { path: "/volunteer", eyebrow: "Get Involved", title: "Volunteer", description: "Share your time and experience to help the next generation of leaders thrive.", image: "/impact/impact-2.jpg", sections: [{ title: "Serve with FKF", body: "Volunteers strengthen programs, mentor young people, support events, and help extend the Foundation’s reach." }, { title: "Ways to contribute", body: "Opportunities vary by program and location.", items: ["Mentoring", "Program support", "Community service", "Professional expertise"] }], cta: { label: "Contact us", href: "/contact" } },
  { path: "/support-us", eyebrow: "Donation", title: "Support Us", description: "Your support helps provide opportunity, mentorship, and resources to young leaders.", image: "/cta/image.jpg", sections: [{ title: "Support this work", body: "Contributions enable the Foundation to advance its mission and reach more young people. A dollar can make a difference in the life of a student." }, { title: "Questions about giving?", body: "Contact donate@franciskoromafoundation.org for donation-related questions." }], cta: { label: "Donate now", href: "/donate" } },
  { path: "/donate", eyebrow: "Support Our Mission", title: "Make a Difference", description: "Help empower the next generation of global leaders and changemakers.", image: "/cta/image.jpg", sections: [{ title: "Your contribution matters", body: "Donations support academic opportunity, mentorship, leadership development, and community engagement." }, { title: "Secure giving", body: "Online gifts are processed through the Foundation’s established external donation provider. Payment processing is not stored in this Phase 1 website." }], cta: { label: "Donate securely", href: "https://www.zeffy.com/" } },
  { path: "/annual-reports", eyebrow: "Resources", title: "Annual Reports", description: "Review the Foundation’s public reporting and milestones.", image: "/impact/impact-7.jpg", sections: [{ title: "Transparency and progress", body: "Annual reports share the Foundation’s activities, development, and impact with supporters and partners." }, { title: "2023 Annual Report", body: "The current public annual report is hosted on Issuu." }], cta: { label: "Read the 2023 report", href: "https://www.issuu.com/" } },
  { path: "/contact", eyebrow: "Contact Us", title: "Let’s Connect", description: "Questions, partnership ideas, and messages are welcome.", image: "/about/about-image.jpg", sections: [{ title: "Foundation contact", body: "Email info@franciskoromafoundation.org. For donation questions, email donate@franciskoromafoundation.org." }, { title: "Organization", body: "The Francis Koroma Foundation is a United States-based 501(c)(3) nonprofit organization." }], cta: { label: "Email the Foundation", href: "mailto:info@franciskoromafoundation.org" } },
  { path: "/privacy-policy", eyebrow: "Legal", title: "Privacy Policy", description: "How the Francis Koroma Foundation website handles visitor information.", sections: [{ title: "Website privacy", body: "This Phase 1 website does not provide user accounts, payment processing, or a newsletter backend. External services may apply their own privacy terms when you follow a link to them." }, { title: "Contact", body: "For privacy questions, contact info@franciskoromafoundation.org." }] },
];

export const pageMap = new Map(pages.map((page) => [page.path, page]));
