"use client";
import { FormEvent, useState } from "react";
import type { SitePage } from "@/lib/site-content";
import type { SiteSettings } from "@/lib/cms";
type Video={id:string;title:string;description:string;video_url:string;thumbnail_url:string|null;published:boolean};
const input="w-full rounded-lg border border-slate-300 px-3 py-2";
export function CmsManager({initialPages,initialSettings,initialVideos,csrfToken}:{initialPages:SitePage[];initialSettings:SiteSettings;initialVideos:Video[];csrfToken:string}){
 const[pages,setPages]=useState(initialPages);const[selected,setSelected]=useState(0);const[settings,setSettings]=useState(initialSettings);const[videos,setVideos]=useState(initialVideos);const[msg,setMsg]=useState("");const[busy,setBusy]=useState(false);const page=pages[selected];
 async function send(method:string,body:object){setBusy(true);const r=await fetch("/api/admin/cms",{method,headers:{"content-type":"application/json","x-csrf-token":csrfToken},body:JSON.stringify(body)});const d=await r.json();setBusy(false);setMsg(r.ok?"Saved successfully.":d.error||"Unable to save");return r.ok?d:null}
 async function savePage(e:FormEvent){e.preventDefault();await send("PUT",{kind:"page",value:{path:page.path,eyebrow:page.eyebrow,title:page.title,description:page.description,image:page.image||null,sections:page.sections,cta:page.cta||null,published:true}})}
 function updatePage(value:SitePage){setPages(old=>old.map((p,i)=>i===selected?value:p))}
 async function addVideo(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const d=await send("POST",{title:f.get("title"),description:f.get("description"),video_url:f.get("video_url"),thumbnail_url:f.get("thumbnail_url")||null,published:true});if(d){setVideos(v=>[...v,d.video]);e.currentTarget.reset()}}
 return <div className="grid gap-8">
  <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-2xl font-bold">Branding and homepage</h2><p className="mt-1 text-slate-600">Change the logo and homepage hero without changing the layout.</p><form onSubmit={async e=>{e.preventDefault();await send("PUT",{kind:"settings",value:{organization_name:settings.organizationName,logo_url:settings.logoUrl,contact_email:settings.contactEmail,hero_title:settings.heroTitle,hero_description:settings.heroDescription,hero_video_url:settings.heroVideoUrl}})}} className="mt-5 grid gap-4 md:grid-cols-2"><label>Organization name<input className={input} value={settings.organizationName} onChange={e=>setSettings({...settings,organizationName:e.target.value})}/></label><label>Contact email<input type="email" className={input} value={settings.contactEmail} onChange={e=>setSettings({...settings,contactEmail:e.target.value})}/></label><label className="md:col-span-2">Logo image URL<input className={input} value={settings.logoUrl} onChange={e=>setSettings({...settings,logoUrl:e.target.value})}/><span className="text-xs text-slate-500">Upload an image in Media Library, copy its URL, and paste it here.</span></label><label className="md:col-span-2">Homepage headline<input className={input} value={settings.heroTitle} onChange={e=>setSettings({...settings,heroTitle:e.target.value})}/></label><label className="md:col-span-2">Homepage description<textarea className={input} rows={4} value={settings.heroDescription} onChange={e=>setSettings({...settings,heroDescription:e.target.value})}/></label><label className="md:col-span-2">Homepage video URL<input className={input} value={settings.heroVideoUrl} onChange={e=>setSettings({...settings,heroVideoUrl:e.target.value})}/></label><button disabled={busy} className="w-fit rounded-lg bg-emerald-700 px-5 py-2 font-semibold text-white">Save branding</button></form></section>
  <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-2xl font-bold">Page editor</h2><select className={`${input} mt-4`} value={selected} onChange={e=>setSelected(Number(e.target.value))}>{pages.map((p,i)=><option key={p.path} value={i}>{p.path} — {p.title}</option>)}</select><form onSubmit={savePage} className="mt-5 grid gap-4"><label>Page label<input className={input} value={page.eyebrow} onChange={e=>updatePage({...page,eyebrow:e.target.value})}/></label><label>Title<input className={input} value={page.title} onChange={e=>updatePage({...page,title:e.target.value})}/></label><label>Description<textarea className={input} rows={3} value={page.description} onChange={e=>updatePage({...page,description:e.target.value})}/></label><label>Hero image URL<input className={input} value={page.image||""} onChange={e=>updatePage({...page,image:e.target.value})}/></label>{page.sections.map((s,i)=><fieldset className="rounded-xl border p-4" key={i}><legend className="px-2 font-semibold">Section {i+1}</legend><input className={input} value={s.title} onChange={e=>updatePage({...page,sections:page.sections.map((x,n)=>n===i?{...x,title:e.target.value}:x)})}/><textarea className={`${input} mt-3`} rows={4} value={s.body} onChange={e=>updatePage({...page,sections:page.sections.map((x,n)=>n===i?{...x,body:e.target.value}:x)})}/></fieldset>)}<button disabled={busy} className="w-fit rounded-lg bg-emerald-700 px-5 py-2 font-semibold text-white">Publish page</button></form></section>
  <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-2xl font-bold">Video library</h2><form onSubmit={addVideo} className="mt-4 grid gap-3 md:grid-cols-2"><input required name="title" placeholder="Video title" className={input}/><input required name="video_url" placeholder="Uploaded video or YouTube URL" className={input}/><input name="thumbnail_url" placeholder="Thumbnail image URL (optional)" className={input}/><input name="description" placeholder="Description" className={input}/><button className="w-fit rounded-lg bg-emerald-700 px-5 py-2 font-semibold text-white">Add video</button></form><div className="mt-5 grid gap-3">{videos.map(v=><div className="flex items-center justify-between rounded-lg border p-3" key={v.id}><div><p className="font-semibold">{v.title}</p><a className="text-sm text-emerald-700" href={v.video_url} target="_blank">Open video</a></div><button onClick={async()=>{if(confirm("Delete this video entry?")){const d=await send("DELETE",{id:v.id});if(d)setVideos(x=>x.filter(y=>y.id!==v.id))}}} className="text-sm text-red-700">Delete</button></div>)}</div></section>{msg&&<div className="fixed bottom-5 right-5 rounded-lg bg-slate-950 px-5 py-3 text-white">{msg}</div>}
 </div>
}
