"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
type Item={id:string;name:string;url:string|null};
export function StorageManager({csrfToken}:{csrfToken:string}){
  const[bucket,setBucket]=useState<"website-media"|"private-documents">("website-media"); const[files,setFiles]=useState<Item[]>([]); const[msg,setMsg]=useState(""); const[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const r=await fetch(`/api/admin/storage?bucket=${bucket}`);if(r.ok)setFiles((await r.json()).files)},[bucket]);
  useEffect(()=>{let cancelled=false;fetch(`/api/admin/storage?bucket=${bucket}`).then(r=>r.ok?r.json():{files:[]}).then(data=>{if(!cancelled)setFiles(data.files)});return()=>{cancelled=true}},[bucket]);
  async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const formElement=e.currentTarget;const form=new FormData(formElement);form.set("bucket",bucket);const r=await fetch("/api/admin/storage",{method:"POST",headers:{"x-csrf-token":csrfToken},body:form});const d=await r.json();setBusy(false);setMsg(r.ok?"Upload complete.":d.error);if(r.ok){formElement.reset();await load()}}
  async function remove(path:string){if(!confirm("Delete this file?"))return;const r=await fetch("/api/admin/storage",{method:"DELETE",headers:{"content-type":"application/json","x-csrf-token":csrfToken},body:JSON.stringify({bucket,path})});setMsg(r.ok?"File deleted.":(await r.json()).error);if(r.ok)await load()}
  return <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-bold">File library</h2><p className="text-sm text-slate-500">Public website images and protected internal documents</p></div><select value={bucket} onChange={e=>setBucket(e.target.value as typeof bucket)} className="rounded-lg border p-2"><option value="website-media">Website media (public)</option><option value="private-documents">Private documents</option></select></div><form onSubmit={upload} className="mt-5 flex flex-wrap gap-3"><input name="file" type="file" required accept={bucket==="website-media"?"image/jpeg,image/png,image/webp,image/gif,image/svg+xml":".pdf,.doc,.docx,.xlsx,.csv"} className="rounded-lg border p-2"/><button disabled={busy} className="rounded-lg bg-emerald-700 px-5 py-2 font-semibold text-white">{busy?"Uploading…":"Upload"}</button></form>{msg&&<p className="mt-3 text-sm">{msg}</p>}<div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{files.map(file=><div key={file.id} className="rounded-lg border p-3"><p className="truncate text-sm font-medium" title={file.name}>{file.name}</p><div className="mt-3 flex gap-2">{file.url&&<a href={file.url} target="_blank" rel="noreferrer" className="rounded border px-2 py-1 text-xs">Open</a>}<button onClick={()=>remove(file.name)} className="rounded border border-red-200 px-2 py-1 text-xs text-red-700">Delete</button></div></div>)}</div></section>
}
