"use client";
import { FormEvent, useEffect, useState } from "react";
type User = { id:string; firstName:string; lastName:string; email:string; phone:string|null; role:string; status:string; lastLogin:string|null; lockedUntil:string|null };
type Log = { id:string; action:string; createdAt:string; ipAddress:string|null; actor:{firstName:string;lastName:string;email:string}|null; targetUser:{firstName:string;lastName:string;email:string}|null };
export function UserManager({ initialUsers, csrfToken }: { initialUsers: User[]; csrfToken: string }) {
  const [users,setUsers]=useState(initialUsers); const [logs,setLogs]=useState<Log[]>([]); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function reload(){ const r=await fetch("/api/admin/users"); if(r.ok) setUsers((await r.json()).users); }
  async function api(url:string,method:string,body?:object){ setBusy(true); setMessage(""); const r=await fetch(url,{method,headers:{"content-type":"application/json","x-csrf-token":csrfToken},body:body?JSON.stringify(body):undefined}); const d=await r.json(); setBusy(false); if(!r.ok){setMessage(d.error||"Request failed");return false} await reload(); return true; }
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const ok=await api("/api/admin/users","POST",Object.fromEntries(f));if(ok){e.currentTarget.reset();setMessage("User created and invitation sent.")}}
  async function changeStatus(u:User,status:string){await api(`/api/admin/users/${u.id}/status`,"PATCH",{status,unlock:false})}
  async function reset(u:User){const password=prompt(`Temporary password for ${u.email} (12+ chars with uppercase, lowercase, number and symbol):`);if(password&&await api(`/api/admin/users/${u.id}/reset-password`,"POST",{temporaryPassword:password}))setMessage("Password reset; the user must change it.")}
  async function edit(u:User){const firstName=prompt("First name:",u.firstName);if(!firstName)return;const lastName=prompt("Last name:",u.lastName);if(!lastName)return;const phone=prompt("Phone (optional):",u.phone||"");const role=prompt("Role: OWNER, ADMINISTRATOR, or EDITOR",u.role)?.toUpperCase();if(!role||!["OWNER","ADMINISTRATOR","EDITOR"].includes(role))return setMessage("Invalid role.");if(await api(`/api/admin/users/${u.id}`,"PUT",{firstName,lastName,phone:phone||null,role}))setMessage("User updated.")}
  async function remove(u:User){if(confirm(`Delete ${u.email}? This cannot be undone.`))await api(`/api/admin/users/${u.id}`,"DELETE")}
  useEffect(()=>{fetch("/api/admin/audit-logs").then(r=>r.ok?r.json():{logs:[]}).then(d=>setLogs(d.logs));},[]);
  return <div className="space-y-8">
    <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Create user</h2><p className="mt-1 text-sm text-slate-500">The account remains invited until the recipient sets a new password.</p>
      <form onSubmit={create} className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><input name="firstName" required placeholder="First name" className="rounded-lg border p-3"/><input name="lastName" required placeholder="Last name" className="rounded-lg border p-3"/><input name="email" type="email" required placeholder="Email address" className="rounded-lg border p-3"/><input name="phone" placeholder="Phone (optional)" className="rounded-lg border p-3"/><select name="role" className="rounded-lg border p-3"><option value="EDITOR">Editor</option><option value="ADMINISTRATOR">Administrator</option><option value="OWNER">Owner</option></select><input name="temporaryPassword" type="password" required placeholder="Temporary password" className="rounded-lg border p-3"/><input name="profilePhoto" type="url" placeholder="Profile photo URL (optional)" className="rounded-lg border p-3 md:col-span-2"/><button disabled={busy} className="rounded-lg bg-emerald-700 p-3 font-semibold text-white disabled:opacity-50">Create & invite</button></form>{message&&<p role="status" className="mt-4 rounded-lg bg-slate-100 p-3 text-sm">{message}</p>}
    </section>
    <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-6"><h2 className="text-xl font-bold">Users</h2><p className="text-sm text-slate-500">{users.length} account{users.length===1?"":"s"}</p></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">User</th><th className="p-4">Role</th><th className="p-4">Status</th><th className="p-4">Last login</th><th className="p-4">Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-t"><td className="p-4"><b>{u.firstName} {u.lastName}</b><div className="text-slate-500">{u.email}</div></td><td className="p-4">{u.role.replace("_"," ")}</td><td className="p-4"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{u.lockedUntil?"LOCKED":u.status}</span></td><td className="p-4 text-slate-500">{u.lastLogin?new Date(u.lastLogin).toLocaleString():"Never"}</td><td className="p-4"><div className="flex flex-wrap gap-2"><button onClick={()=>edit(u)} className="rounded border px-2 py-1">Edit</button><button onClick={()=>changeStatus(u,u.status==="ACTIVE"?"SUSPENDED":"ACTIVE")} className="rounded border px-2 py-1">{u.status==="ACTIVE"?"Suspend":"Activate"}</button>{u.lockedUntil&&<button onClick={()=>api(`/api/admin/users/${u.id}/status`,"PATCH",{status:u.status,unlock:true})} className="rounded border px-2 py-1">Unlock</button>}<button onClick={()=>reset(u)} className="rounded border px-2 py-1">Reset password</button><button onClick={()=>api(`/api/admin/users/${u.id}/send-invitation`,"POST")} className="rounded border px-2 py-1">Invite</button><button onClick={()=>remove(u)} className="rounded border border-red-200 px-2 py-1 text-red-700">Delete</button></div></td></tr>)}</tbody></table></div></section>
    <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-6"><h2 className="text-xl font-bold">Recent activity</h2><p className="text-sm text-slate-500">Login history and user-management audit trail</p></div><div className="max-h-96 overflow-auto">{logs.map(log=><div key={log.id} className="grid gap-1 border-b px-6 py-3 text-sm md:grid-cols-4"><b>{log.action.replaceAll("_"," ")}</b><span>{log.actor?`${log.actor.firstName} ${log.actor.lastName}`:"System"}</span><span className="text-slate-500">{log.targetUser?.email||"—"}</span><span className="text-slate-500">{new Date(log.createdAt).toLocaleString()}</span></div>)}</div></section>
  </div>;
}
